name: Python Hello World
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v4
      - name: Restore dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: python-files
          path: |
            hello_world.py
            requirements.txt
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: python-files
      - name: Run python script
        run: python3 hello_world.py
