name: Python Hello World
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      shortHash: ${{ steps.publish.outputs.gitHash }}
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v4
      - name: Publish commit hash
        id: publish
        run: |
          git_hash=$(git rev-parse --short "$GITHUB_SHA")
          git_branch=${GITHUB_REF#refs/heads/}
          echo "gitHash=$git_hash" >> $GITHUB_OUTPUT
          echo $git_hash
      - name: Restore dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Debug artifact name
        run: |
          echo "Artifact name: python-files-${{ steps.publish.outputs.gitHash }}"
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: python-files-$gitShortHash
          path: |
            hello_world.py
            requirements.txt
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: python-files-${{ needs.build.outputs.short-hash }}
      # - name: Run python script
      #   run: python3 hello_world.py
